Feature
verissimohenry/newyorktime pull request #5
Opened 2021-02-19 20:54 UTC by verissimohenry

2021-02-19 21:17 UTC, wathigo commented
> # Invalid PR
The pull request has been marked as invalid since linter checks are failing. 
Let's ensure linters checks are passing.

2021-02-20 21:20 UTC, elmejdki requested changes
# status: require changes :recycle: 

Hi, there I have noticed that you have skipped several requirements from the [previous TSE](https://github.com/verissimohenry/newyorktime/pull/3#pullrequestreview-592475410) Please return back and make sure you do them, also I have left for you some of the changes to do.

Please check the comments below.
:point_down: :point_down: :point_down: :point_down: :point_down: 

## Require Changes :red_circle::

- [ ] Please use the same colors as in the original page as well as the layout and position elements correctly.

### Please make all the required changes before you submit another code review.
## Happy Coding :tophat:

2021-02-21 10:38 UTC, bini-i requested changes
# Status: Changes Required :yellow_circle: 
### Hello  @verissimohenry :wave: 

### Thanks for working on the changes suggested and your project passes most of the requirements, but you still can improve your project. 
#### Please work on all requirements suggested by previous TSEs and I have replicated the remaining requirements below so that you can refer them easily.

- [ ] First of all, always provide a description of the features you have added in your pull request. Please take a step back and read a lesson [here](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/)

- [ ] Please write a descriptive and well-structured README file for your project (Also give yourself a quick reminder from this [link](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/))

#### If you have any question kindly reach me on slack @Binyam Hailemeskel

### HAPPY CODING :computer: :blush: 

> #### Reviewed by Binyam Hailemeskel (TSE)
> GitHub: [@bini-i](https://github.com/bini-i)
> Twitter: [@binyamshewa](https://twitter.com/binyamshewa)
> LinkedIn: [LinkedIn](https://www.linkedin.com/in/binyam-hailemeskel-728048151/)

2021-02-21 11:17 UTC, verissimohenry commented
Add a well-descriptive README file to my project.

2021-02-21 19:32 UTC, Forison requested changes
## Status::Change Required🛑

# 🙋‍♂️ Team 

* [ ] As mentioned in the previous review, you need to add a descriptive Readme for the page, Let us use the format, given in the [pathright by Microverse](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/).

* [ ] Some portions of the page do not look like  the original :
- Let us put some padding around the button in the navbar to make them align to the center of the navbar.
- There should be some margin at the top of the button.
![2](https://user-images.githubusercontent.com/29695661/108635414-468ece80-744d-11eb-8955-3daac77f9170.png)
- There should be some margin at the top to make it align to the center of the page.
![Screenshot from 2021-02-21 13-58-48](https://user-images.githubusercontent.com/29695661/108635415-47bffb80-744d-11eb-9834-d60a5f1abb68.png)

You can use the `align-items-center` attribute on the parent navbar to have element aligned to the center

- Let us take a second look at this part of the page 
![Screenshot from 2021-02-21 14-03-41](https://user-images.githubusercontent.com/29695661/108635536-d6cd1380-744d-11eb-9143-9263def23c39.png)

let us compare it to the original 
![Screenshot from 2021-02-21 14-05-35](https://user-images.githubusercontent.com/29695661/108635564-03812b00-744e-11eb-96ce-8fa37b3c5c8c.png)

- Let us take a look at theory of inflation section

original
![Screenshot from 2021-02-21 14-11-55](https://user-images.githubusercontent.com/29695661/108635767-324bd100-744f-11eb-8d35-7d74f4bb783f.png)
clone
![Screenshot from 2021-02-21 14-15-47](https://user-images.githubusercontent.com/29695661/108635808-70e18b80-744f-11eb-9f3f-740890329ae1.png)

#### That is it, kindly make the changes and submit a re-review👷.

#### Happy coding 👨‍💻

Addo Forison

2021-02-21 19:32 UTC, Forison commented on index.html
> +            <h2>The Theory of Inflation</h2>
moving 195 to 200 down

2021-02-21 19:32 UTC, Forison commented on index.html
>              <section class="graphics">
to having 

`

            <section class="graphics">
              <h2>The Theory of Inflation</h2>
              <p class="summary-text">
                  <span class="summary-text">Astronomers have found evidence to support the theory of inflation,
                      which explains how the universe expanded so uniformly and so quickly
                      in the instant after the Big Bang 13.8 billion years ago.</span>
              </p>
<h2 hidden></h2>
                <div class="img-tool">
                    <img src="image.png/img1.png" alt="first image" />
                    <p class="img-p">
                        <strong>THE UNIVERSE</strong> is just under 14 billion years old.
                        From our position in the Milky Way galaxy, we can observe a sphere
                        that is now about 92 billion light-years across. But there's a
                        mystery. Wherever we look, the universe has an even temperature.
                    </p>
                </div>
.....
`
will fix the theory of inflation UI flaw.

2021-02-22 08:47 UTC, closed without merging

2021-02-22 09:15 UTC, verissimohenry commented
Done.

On Sun, 21 Feb 2021 at 20:33, Addo Forison <notifications@github.com> wrote:

> *@Forison* requested changes on this pull request.
> Status::Change Required🛑 🙋‍♂️ Team
>
>    -
>
>    As mentioned in the previous review, you need to add a descriptive
>    Readme for the page, Let us use the format, given in the pathright by
>    Microverse
>    <https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/>
>    .
>    -
>
>    Some portions of the page do not look like the original :
>
>
>    - Let us put some padding around the button in the navbar to make them
>    align to the center of the navbar.
>    - There should be some margin at the top of the button.
>    [image: 2]
>    <https://user-images.githubusercontent.com/29695661/108635414-468ece80-744d-11eb-8955-3daac77f9170.png>
>    - There should be some margin at the top to make it align to the
>    center of the page.
>    [image: Screenshot from 2021-02-21 13-58-48]
>    <https://user-images.githubusercontent.com/29695661/108635415-47bffb80-744d-11eb-9834-d60a5f1abb68.png>
>
> You can use the align-items-center attribute on the parent navbar to have
> element aligned to the center
>
>    - Let us take a second look at this part of the page
>    [image: Screenshot from 2021-02-21 14-03-41]
>    <https://user-images.githubusercontent.com/29695661/108635536-d6cd1380-744d-11eb-9143-9263def23c39.png>
>
> let us compare it to the original
> [image: Screenshot from 2021-02-21 14-05-35]
> <https://user-images.githubusercontent.com/29695661/108635564-03812b00-744e-11eb-96ce-8fa37b3c5c8c.png>
>
>    - Let us take a look at theory of inflation section
>
> original
> [image: Screenshot from 2021-02-21 14-11-55]
> <https://user-images.githubusercontent.com/29695661/108635767-324bd100-744f-11eb-8d35-7d74f4bb783f.png>
> clone
> [image: Screenshot from 2021-02-21 14-15-47]
> <https://user-images.githubusercontent.com/29695661/108635808-70e18b80-744f-11eb-9f3f-740890329ae1.png>
> That is it, kindly make the changes and submit a re-review👷. Happy
> coding 👨‍💻
>
> Addo Forison
> ------------------------------
>
> In index.html
> <https://github.com/verissimohenry/newyorktime/pull/5#discussion_r579852278>
> :
>
> >
>
> +        </div>
>
> +        <br>
>
> +        <section>
>
> +            <h2>The Theory of Inflation</h2>
>
>
> moving 195 to 200 down
> ------------------------------
>
> In index.html
> <https://github.com/verissimohenry/newyorktime/pull/5#discussion_r579852481>
> :
>
> >
>
> +        </div>
>
> +        <br>
>
> +        <section>
>
> +            <h2>The Theory of Inflation</h2>
>
> +            <p class="summary-text">
>
> +                <span class="summary-text">Astronomers have found evidence to support the theory of inflation,
>
> +                    which explains how the universe expanded so uniformly and so quickly
>
> +                    in the instant after the Big Bang 13.8 billion years ago.</span>
>
> +            </p>
>
>              <section class="graphics">
>
>
> to having
>
> `
>
>         <section class="graphics">
>
>           <h2>The Theory of Inflation</h2>
>
>           <p class="summary-text">
>
>               <span class="summary-text">Astronomers have found evidence to support the theory of inflation,
>
>                   which explains how the universe expanded so uniformly and so quickly
>
>                   in the instant after the Big Bang 13.8 billion years ago.</span>
>
>           </p>
>
>
> [image: first image] <http://image.png/img1.png>
>
> *THE UNIVERSE* is just under 14 billion years old. From our position in
> the Milky Way galaxy, we can observe a sphere that is now about 92 billion
> light-years across. But there's a mystery. Wherever we look, the universe
> has an even temperature.
> ..... ` will fix the theory of inflation UI flaw.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/verissimohenry/newyorktime/pull/5#pullrequestreview-594871626>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AP4IZSM4C5ODZ2OAWXYE5LLTAFNW5ANCNFSM4X5AQANA>
> .
>